language: generic
sudo: true
services:
  - docker
before_install:
  - docker build -t asimamalani/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true asimamalani/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"
  app: "react-app"
  env: "ReactApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-054031165989"
  bucket_path: "react-app"
  on:
    branch: "master"
